### PR TITLE
Released/handle broken conflicts

### PR DESCRIPTION
**Pull request by karenetheridge**
This resolves RT#75486 (and replaces the earlier branch that I mention in the ticket, more than a year ago.)

I also released this as 0.006-TRIAL (unauthorized of course), to try to get some cpantesters reports.

### CODE REVIEW

**Comment by doy** [comment]
Can you rebase this again?

**Comment by karenetheridge** [comment]
I'm not sure if I can, as it looks like you've somewhat implemented the same idea but in a different way.

However, my squashed/handle_broken_conflicts branch should contain the tidied form of these commits, including a 0.06-TRIAL tag that matches what was released. It also contains some improvements haarg made to this code, and some dist.ini edits to make the tag and Changes entry come out right.

I'm just not sure how to merge those changes with what you've done (and released) this past week.

**Comment by karenetheridge** [comment]
Making a stab at it now... after re-reading what I did before...

**Comment by karenetheridge** [comment]
Ok, reset --hard and force-pushed this branch from commit  3c5e363 to bc6db63. The diff looks good and tests pass.

**Comment by doy** [comment]
Can you rebase this instead of merging? It's hard to see what the changes are with the history looking like this.

**Comment by karenetheridge** [comment]
done.

**Comment by doy** [comment]
Thanks, merged.

**Pull request closed without merging**
